### ISSUE TITLE
Trademark violation

### ISSUE THREAD

**Issue by Lucent** [AlirezaKJ/theptable.com#1]
Including "ptable" in this repo and domain as it refers to an online electronic periodic table is in violation of US trademark serial number 87536072. You can create an online periodic table website, but you cannot use this domain to host it. You can keep this domain and put something else up like a poker table, but taken together, this violates the trademark.

Let me know when you have renamed this and dropped the domain so I do not have to contact GitHub and ICANN.

**Comment by AlirezaKJ** [comment]
the domain https://theptable.com/ will be out on 16 of march and this project move to https://alirezakj.com/ subdomains but the project name wouldn't change

(this decision was made before you open this issue)

**Comment by Lucent** [comment]
You need to rename the repository as well. I will submit a takedown request to GitHub since you seem unwilling to comply.

**Comment by AlirezaKJ** [comment]
its "theptable" and they wouldn't do such thing for a intern project you can call git if you want.
